export default {
    SET_TABLEDATA(state,pyload){
        state.tableData=pyload
    },
    SET_ROLEDATA(state,pyload){
        state.roleData=pyload
    },
    SET_USERDATA(state,pyload){
        state.userData=pyload
    },
    SET_CATEDATA(state,pyload){
        state.cateData=pyload
    },
    SET_SPECSDATA(state,pyload){
        state.specsData=pyload
    },
    SET_GOODSDATA(state,pyload){
        state.goodsData=pyload
    },
    SET_BANNERDATA(state,pyload){
        state.bannerData=pyload
    },
    SET_SECKDATA(state,pyload){
        state.seckData=pyload
    }
}